language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gmurop/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gmurop/react-test npm test

after_success:
  - docker build -t gmurop/multi-client ./client
  - docker build -t gmurop/multi-nginx ./nginx
  - docker build -t gmurop/multi-server ./server
  - docker build -t gmurop/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push gmurop/multi-client
  - docker push gmurop/multi-nginx
  - docker push gmurop/multi-server
  - docker push gmurop/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-200089665122
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
