version: "3"
services:
  client:
    image: "gmurop/multi-client"
    mem_limit: 128m
  api:
    image: "cygnetops/multi-server"
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "gmurop/multi-worker"
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "gmurop/multi-nginx"
    mem_limit: 128m
    ports:
      - "80:80"